# Generated by Django 5.1.3 on 2026-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='meta', max_length=32)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('page_id', models.CharField(blank=True, max_length=64)),
                ('form_id', models.CharField(blank=True, max_length=64)),
                ('leadgen_id', models.CharField(blank=True, max_length=64)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'leadgen_id'], name='webhooks_we_provide_9a1094_idx'), models.Index(fields=['status', 'received_at'], name='webhooks_we_status_4d802a_idx')],
            },
        ),
    ]
