# Generated by Django 5.1.3 on 2026-04-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facebook_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('require_email_opt_in', models.BooleanField(default=True)),
                ('require_sms_opt_in', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_forms', models.ManyToManyField(blank=True, related_name='automation_rules', to='facebook_integration.leadform')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='facebook_integration.facebookpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(blank=True, limit_choices_to={'channel': 'email'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_rules', to='automations.messagetemplate')),
                ('sms_template', models.ForeignKey(blank=True, limit_choices_to={'channel': 'sms'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_rules', to='automations.messagetemplate')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
