# Generated by Django 5.1.3 on 2026-04-17 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'channel': 'whatsapp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_rules', to='automations.messagetemplate'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='twilio_content_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='twilio_content_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=16),
        ),
    ]
